#
# MSI DDSS 2021/2022 - Assignment 2
# The code and resources available in this repository are to be used in the scope of the DDSS course.
#
# Authors: Nuno Antunes <nmsa@dei.uc.pt>, João Antunes <jcfa@dei.uc.pt>
#
version: "3.8"

services:
  db:
    build: ./postgresql
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: ./python
    container_name: web
    volumes:
      - "./python/app:/app"
    expose:
      - "5000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./python/app/certificates:/certificates
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web
